
blk_dev_apple-y							+= api.o blk_dev.o

obj-$(CONFIG_BLK_DEV_APPLE)				+= blk_dev_apple.o
obj-$(CONFIG_BLK_DEV_APPLE_VSVFL)		+= vsvfl.o
obj-$(CONFIG_BLK_DEV_APPLE_YAFTL)		+= yaftl/
obj-$(CONFIG_BLK_DEV_APPLE_LEGACY_VFL)	+= vfl.o
#obj-$(CONFIG_BLK_DEV_APPLE_LEGACY_FTL)	+= ftl/
obj-$(CONFIG_BLK_DEV_H2FMI)				+= h2fmi.o
